import { readFileSync } from 'node:fs';

export const groups = [
  { title: 'Foundation and Site configuration', from: 23, to: 25 },
  { title: 'Public single-ticket journey', from: 26, to: 33 },
  { title: 'Recovery, operations, refunds, and totals', from: 34, to: 45 },
  { title: 'Private approval and Wallet', from: 46, to: 49 },
  { title: 'Public group purchase', from: 50, to: 50 },
  { title: 'Release verification', from: 51, to: 55 },
];
export const tickets = JSON.parse(readFileSync(new URL('./tickets.json', import.meta.url)));

// Explicit mapping: route availability reflects inspected implementation, not issue closure.
// Generic action paths additionally list which actions currently exist.
const mapping = [
  ['GET /v1/public/events', [26, 27, 33, 41], true],
  ['GET /v1/public/events/{event_id}', [26, 27, 33, 40, 41], true],
  ['GET /v1/public/orders/{order_token}', [28, 30, 31, 33, 38, 39, 41, 42, 47, 50], true],
  ['GET /v1/public/tickets/{ticket_token}', [30, 31, 32, 33, 39, 41, 42, 47, 50], true],
  ['GET /v1/public/access-requests/{access_request_token}', [46, 47], true],
  ['GET /v1/public/tickets/{ticket_token}/apple-wallet-data', [40, 48, 49, 50], true, 'Returns unsigned current Ticket data; pass signing and device registration remain Site-owned.'],
  ['POST /v1/public/events/{event_id}/quotes', [28, 33, 47, 50], true, 'Public quantity 1–8 and approved-private quantity 1 are available.'],
  ['POST /v1/public/orders', [28, 33, 47, 50], true, 'Public quantity 1–8 and approved-private quantity 1 are available.'],
  ['POST /v1/public/events/{event_id}/access-requests', [46], true],
  ['POST /v1/public/order-recovery', [38, 39], true, 'The local correction-race workflow requests recovery and verifies the claimed temporary link before a Site worker can send.'],
  ['GET /v1/admin/events', [26, 41], true],
  ['GET /v1/admin/events/{event_id}', [26, 27, 40, 41, 46, 47, 49, 50], true],
  ['POST /v1/admin/events', [26, 46, 47, 50], true],
  ['PATCH /v1/admin/events/{event_id}', [26, 27, 40, 46, 47, 49, 50], true],
  ['POST /v1/admin/events/{event_id}/actions/{action}', [26, 27, 41, 47, 50], true, 'publish, archive, stop_sales, resume_sales, and cancel are available.'],
  ['PUT /v1/admin/events/{event_id}/provider-mappings/{connection_id}', [29, 44], true],
  ['DELETE /v1/admin/events/{event_id}/provider-mappings/{connection_id}', [29, 44], true],
  ['GET /v1/admin/events/{event_id}/orders', [35, 36, 37, 39, 41, 43], true],
  ['GET /v1/admin/orders/{order_id}', [35, 36, 37, 39, 42, 43, 44, 50], true],
  ['GET /v1/admin/orders/{order_id}/payment-status', [29, 30, 33, 34, 35, 36, 42], true],
  ['GET /v1/admin/events/{event_id}/tickets', [32, 43, 50], true],
  ['GET /v1/admin/events/{event_id}/totals', [42, 43, 45], true],
  ['POST /v1/admin/events/{event_id}/ticket-lookup', [32, 39, 50, 51], true],
  ['POST /v1/admin/events/{event_id}/admissions', [32, 33, 41, 42, 47, 48, 49, 50, 51, 53, 54], true],
  ['POST /v1/admin/orders/{order_id}/actions/{action}', [36, 37, 39], true, 'retry_ticket_issuance, guarded resend_ticket_email, and verified correct_delivery_email are available.'],
  ['GET /v1/admin/tickets/{ticket_id}/apple-wallet-data', [48, 49], true, 'Returns unsigned current Ticket data; pass signing and device registration remain Site-owned.'],
  ['GET /v1/admin/events/{event_id}/access-requests', [46], true],
  ['GET /v1/admin/access-requests/{request_id}', [46], true],
  ['PATCH /v1/admin/access-requests/{request_id}', [46], true],
  ['POST /v1/admin/access-requests/{request_id}/actions/{action}', [46, 47], true],
  ['GET /v1/admin/payment-configuration', [24, 29, 44], true],
  ['GET /v1/admin/payment-connections/{connection_id}', [24, 29, 34, 44], true],
  ['GET /v1/admin/payment-attempts/{attempt_id}', [29, 30, 34, 35, 44], true],
  ['GET /v1/admin/payment-attempts', [34, 35, 45], true, 'Use requires_verification=true for checkout recovery work or requires_report_work=true for unapplied payment reports; both filters are Site-scoped and cursor-paginated.'],
  ['POST /v1/admin/orders/{order_id}/payment-attempts', [29, 33, 34, 44, 47, 50], true],
  ['POST /v1/admin/payment-attempts/{attempt_id}/checkout-reference', [29, 33, 34, 44, 47, 50], true],
  ['POST /v1/admin/payment-attempts/{attempt_id}/payment-reports', [30, 33, 34, 35, 41, 44, 47, 50], true],
  ['POST /v1/admin/payment-attempts/{attempt_id}/setup-failure', [29, 34], true],
  ['POST /v1/admin/payment-attempts/{attempt_id}/closure-reports', [29, 34, 41, 44], true],
  ['POST /v1/admin/payment-attempts/{attempt_id}/actions/resolve', [35], true],
  ['POST /v1/admin/orders/{order_id}/refund-reports', [42, 44, 45, 54], true],
  ['POST /v1/admin/orders/{order_id}/fee-reports', [43, 45, 54], true],
  ['POST /v1/admin/orders/{order_id}/fee-confirmations', [43, 45, 54], true],
  ['GET /v1/admin/notification-jobs', [25, 31, 37, 38, 39, 40, 41, 45, 46, 47, 49, 50], true],
  ['GET /v1/admin/notification-jobs/{job_id}', [25, 31, 37, 45, 49, 50], true],
  ['POST /v1/admin/notification-jobs/claims', [25, 31, 37, 38, 40, 41, 45, 46, 49, 50], true],
  ['POST /v1/admin/notification-jobs/claims/{claim_id}/renew', [25, 31, 37, 45, 49], true],
  ['POST /v1/admin/notification-jobs/{job_id}/outcome-reports', [25, 31, 37, 38, 40, 41, 45, 46, 49, 50], true],
  ['POST /v1/admin/notification-jobs/{job_id}/delivery-reports', [25, 31, 37, 38, 40, 41, 45, 46, 50], true],
];
export const routes = mapping.map(([route, ticketNumbers, implemented, note]) => ({
  route, tickets: ticketNumbers, implemented,
  note: note ?? (implemented ? 'Implemented HTTP route; workflow/environment prerequisites still apply.' : 'Documented contract; no handler in this revision.'),
}));

const local = (id, ticket, title, steps, extra = {}) => ({ id, ticket, title, steps, profiles: ['simulation'], ...extra });
export const workflows = [
  local('service', 23, 'Read the local service through its API', ['Read Site configuration and record the HTTP response.'], { scope: 'HTTP service observation. Database migration, privacy, and restart persistence require separate operator evidence.' }),
  local('configuration', 24, 'Site configuration, authentication, and isolation', ['Read the test connection assigned to both Sites.', 'Reject a missing key.', 'Create a synthetic paid Order and Ticket, then reject cross-Site IDs, related records, access tokens and shared-provider reference reuse.'], { otherSite: true }),
  local('durable-jobs', 25, 'Claim, renew, overlap, and process notification work', ['Create a paid single-ticket fixture through HTTP.', 'Inspect the bounded Ticket-email frontier and its saved run evidence.', 'Reconcile only a Local simulation unknown whose matching passed run proves no provider call or message reference exists; otherwise stop for verification.', 'Claim the available work, renew the target lease, and verify an overlapping worker cannot claim it.', 'Report synthetic dispatch and delivery, then invoke the existing bounded HP-OS scheduler.'], { scope: 'Lease/API rehearsal. Saved-run reconciliation is limited to synthetic Local simulation evidence; Sandbox and unverified dispatches remain blocked. Process restart and five-minute lease expiry require timed follow-up evidence.' }),
  local('events', 26, 'Staff draft, publish, discover, and archive', ['Create and replay an incomplete draft.', 'Keep draft out of public reads.', 'Save and publish complete details.', 'Read staff and public lists.', 'Archive a separately created ended Event and preserve its direct public page.']),
  local('sales', 27, 'Staff sales controls and Reservation capacity', ['Publish a configured local Event.', 'Stop and resume sales with versions.', 'Reserve one Ticket.', 'Reject capacity below the committed floor.', 'Preserve the accepted Order price after an Event edit.']),
  local('reservation', 28, 'Buyer quote and replay-safe unpaid Order', ['Quote one Ticket without reserving capacity.', 'Create and replay an unpaid Order.', 'Reject used quotes and conflicting key reuse.', 'Race two Orders for one remaining Ticket.']),
  local('checkout', 29, 'Site checkout, closure, and safe replacement', ['Create the HP-OS attempt before the simulated provider.', 'Reject a concurrent unresolved attempt.', 'Register the simulated checkout reference.', 'Report verified simulated closure.', 'Replace within the original window.', 'Reject unsafe setup failure and accept verified closure.'], { scope: 'Catalogless simulation. Provider mappings and real account eligibility remain separate checks.' }),
  local('payment', 30, 'Verified simulated payment and independent Ticket access', ['Read confirmation-pending Order with no Tickets.', 'Report synthetic verified payment.', 'Invoke bounded issuance recovery if needed.', 'Verify exactly one Ticket and separate page/QR tokens.', 'Replay payment without duplicate Tickets.'], { scope: 'Synthetic payment evidence. Deliberately interrupted issuance cannot be injected through the current public API.' }),
  local('delivery', 31, 'Site delivery and buyer pages', ['Create one paid Ticket.', 'Claim the initial email job and verify dispatch separately from delivery.', 'Render Fake LMNL Order/Ticket links.', 'Read independent Order and Ticket pages.']),
  local('admission', 32, 'Staff lookup, simultaneous scans, and safe replay', ['Look up by reference and email without access tokens.', 'Reject invalid and wrong-Event QR submissions.', 'Submit two concurrent scans; exactly one may succeed.', 'Replay the successful scan with its original key.', 'Reject a new scan and manual entry for the admitted Ticket.'], { scope: 'HTTP concurrency rehearsal. Camera, physical-device, role permissions, canceled/refunded, and offline-device checks remain separate.' }),
  local('journey', 33, 'Connected public single-ticket rehearsal', ['Create and publish an Event, quote one Ticket, and reserve it in an unpaid Order.', 'Register a provider checkout whose total matches the accepted Order before payment.', 'Show the Order with no Ticket before payment confirmation.', 'Verify payment, issue exactly one Ticket, and preserve that identity on a repeated payment report.', 'Dispatch the initial email and record delivery separately from the dispatch response.', 'Open the Order page and individual Ticket QR page, then admit once and reject repeat entry.'], { profiles: ['simulation', 'sandbox'], scope: 'Simulation records synthetic provider and email evidence. Sandbox requires explicit Square checkout completion, verified payment and actual Resend delivery. Both profiles are local rehearsal evidence; neither establishes LMNL device or release proof.' }),
  local('closure', 34, 'Closure and replacement rehearsal', ['Keep an unresolved attempt exclusive.', 'Report simulated provider closure.', 'Create one replacement without extending the Order deadline.'], { scope: 'Closure subset. The separate verification-frontier workflow covers unresolved-attempt discovery; provider closure remains simulated.' }),
  local('recovery-frontier', 34, 'Discover an unresolved checkout frontier', ['Create a payment attempt and register a synthetic provider checkout.', 'Record an unknown provider outcome.', 'Discover the attempt through the Site-scoped verification frontier, including its deadline and frozen connection.', 'Confirm a replacement attempt remains blocked while the provider result is unresolved.', 'Run the bounded scheduler and record its verification count.'], { scope: 'Synthetic HTTP boundary. Provider closure, restart, delayed confirmation, deadline expiry and last-capacity restoration remain cutover or database proof.' }),
  local('conflict', 35, 'Investigate and resolve conflicting payment evidence', ['Create a synthetic provider checkout before payment.', 'Submit contradictory payment evidence before fulfillment.', 'Verify the conflict, durable issue, and verification frontier are visible to staff while no Ticket is issued.', 'Reject a stale and an invalid guarded resolution.', 'Apply a valid verified resolution and confirm one Ticket is issued.', 'Verify resolved conflict history is absent from the requires_report_work=true frontier.', 'Replay the resolution and submit delayed evidence without regressing the paid Order.', 'Verify the unapplied delayed report is discoverable through the requires_report_work=true frontier.'], { scope: 'Synthetic HP-OS and Fake LMNL staff evidence. Provider verification, LMNL durable outbox interruption, and cutover proof remain deferred.' }),
  local('issuance-recovery', 36, 'Recover a paid Order awaiting Tickets', ['Create a paid single-ticket Order through the Fake boundary.', 'Read the staff Order view with its Ticket and durable notification evidence.', 'Run the bounded scheduler without visitor traffic and verify it does not duplicate the completed Order.', 'Reject a guarded retry for an already-issued Order without creating another Ticket or email job.'], { scope: 'Synthetic HP-OS and Fake LMNL staff evidence. The Fake boundary does not inject database failures; deliberate automatic and guarded interruption/recovery runs only in pnpm verify:events against local PostgreSQL. Provider proof, hosted worker proof, and cutover testing remain deferred.' }),
  local('delivery-recovery', 37, 'Recover failed Ticket email and correct delivery address', ['Create a paid single-ticket Order through the Fake boundary.', 'Record a confirmed delivery failure and request a guarded resend of the existing Tickets.', 'Verify the resend preserves Ticket identity and retains the original failed job.', 'Correct the delivery email with a reason and verification reference.', 'Verify checkout identity, Ticket identity, QR and admission history remain unchanged while old Order access is replaced.', 'Mark the new dispatch unknown and verify a second resend is rejected until provider or durable-log verification.'], { scope: 'Synthetic HP-OS and Fake LMNL staff evidence. Provider delivery, hosted workers, actual email, and cutover testing remain deferred.' }),
  local('delivery-correction', 39, 'Correct delivery email without changing entry rights', ['Create a paid single-ticket Order using a unique current address.', 'Claim a temporary recovery email for the Order before staff correction.', 'Correct the address with a reason and verification reference after confirmed delivery failure.', 'Verify old normal and temporary Order links fail, while the current email lookup returns the same Order and Ticket.', 'Report the claimed stale recovery job as permanently skipped without sending an email.', 'Verify the replacement Order and Ticket links keep the Ticket ID, QR payload, and Admission history.'], { scope: 'Synthetic HP-OS and Fake LMNL HTTP boundaries. The worker-link check uses the local public API response; private approval and Wallet-device integration, hosted workers, actual email, and cutover testing remain deferred.' }),
  local('unknown-email', 37, 'Retain unknown dispatch for verification', ['Claim a new Ticket-email job.', 'Report unknown dispatch.', 'Verify requires_verification remains true.', 'Do not resend until provider or durable-log verification clears the state.'], { scope: 'Unknown-dispatch subset. It intentionally leaves the job unresolved and does not claim provider or cutover proof.' }),
  local('arrival-change', 40, 'Notify buyers when Event arrival details change', ['Create a public Event whose check-in opening follows Event start.', 'Create a paid Order and Ticket, then move Event time and venue.', 'Verify the default check-in opening follows the new start time.', 'Verify one durable event_changed job per paid Order with the exact changed fields.', 'Verify Wallet update data carries the current version.'], { scope: 'Synthetic local API evidence. LMNL rendering/delivery, hosted interruption, and cutover evidence remain deferred.' }),
  local('cancellation', 41, 'Cancel an Event without implying a refund', ['Create paid and unpaid Orders on one Event.', 'Cancel the Event and verify sales and Admission stop.', 'Verify safe unpaid Reservation release and a durable cancellation notice for the paid Order.', 'Confirm refund status remains separate from cancellation.'], { scope: 'Synthetic local API evidence. Provider closure/refund, buyer delivery, late-charge races, and cutover evidence remain deferred.' }),
  local('refund', 42, 'Apply synthetic refund reports to Ticket eligibility', ['Report a partial refund and confirm the Ticket remains admissible.', 'Complete a full refund and verify the Ticket remains in history but cannot be admitted.', 'Verify unsigned Wallet data is voided and unadmitted capacity is restored once.'], { scope: 'Synthetic refund reports only; no provider refund is initiated or verified.' }),
  local('reporting', 43, 'Read Event operations and report fee totals', ['Read Event Order and Ticket lists plus totals.', 'Confirm missing fee evidence remains pending.', 'Report synthetic payment/refund fee components and confirmations.', 'Verify totals reflect reported amounts without treating expected fees as settlement proof.'], { scope: 'Synthetic fee reports only; no provider settlement is verified.' }),
  local('connection-history', 44, 'Preserve Order payment mapping history', ['Create an Order and attempt with the current Event mapping.', 'Replace the Event mapping for future Orders.', 'Verify the existing Order and attempt retain the original mapping.', 'Verify a new Order uses the replacement mapping.'], { scope: 'Checks Event mapping snapshots only. Operator connection assignment, historical provider access, recovery/refund execution, and cross-Site integration evidence remain separate.' }),
  local('private-approval', 46, 'Request and manage private Event approval', ['Create a private Event and submit an attendee Access Request.', 'Approve one request and confirm no capacity is reserved.', 'Reject a duplicate request without queuing an approval email.', 'Undo and reapprove the first request, invalidating the old link and issuing a replacement.'], { scope: 'Synthetic local API and queued-job evidence. Permission checks and actual email delivery remain separate.' }),
  local('private-purchase', 47, 'Complete one approved private purchase', ['Use an approved link to create a one-Ticket quote and unpaid Order.', 'Keep the approved attendee separate from purchaser identity.', 'Pay, issue and admit one Ticket.', 'Reject a second purchase after approval is consumed.'], { scope: 'Synthetic local payment and email boundary. Provider, email, permission, hosted-worker and cutover evidence remain separate.' }),
  local('wallet-data', 48, 'Read current unsigned Wallet data', ['Read public-token and Site-admin Wallet data.', 'Verify both expose the same version and stable QR without purchaser email.', 'Admit the Ticket and verify current data reports it used.'], { scope: 'Unsigned data only; signing, account eligibility, device installation and device proof remain Site-owned.' }),
  local('wallet-updates', 49, 'Queue Wallet updates after operational changes', ['Admit a Ticket and verify an update job contains the current data version.', 'Edit Event venue details and verify the same Ticket receives a newer data version.'], { scope: 'Checks durable HP-OS update-job payloads only; Apple signing, push, device registration and hosted worker proof remain Site-owned.' }),
  local('group-purchase', 50, 'Buy and issue a public group of Tickets', ['Check quantity-one and quantity-eight quotes and reject quantity nine.', 'Quote three public Tickets without reserving capacity.', 'Create one Order and Reservation for all three, preserving buyer identity, the checkout deadline, and the quantity-scaled total.', 'Verify payment produces the complete, ordered Ticket set and one initial Order email job.', 'Open the Order and each independent Ticket page and unsigned Wallet data, then admit every Ticket once and reject repeat scans.', 'Race two one-Ticket Orders for a separate Event with one remaining unit and confirm exactly one Reservation succeeds.'], { scope: 'Synthetic local HTTP, payment and email evidence. Run after the required single-ticket, recovery, private-purchase and Wallet stages; provider, email, device, hosted and cutover proof remain separate.' }),
];
const reasons = {
  33: 'Full gate requires actual LMNL/provider/email and device evidence, beyond the Fake LMNL rehearsal.',
  34: 'The Fake LMNL workflow covers the synthetic verification frontier. Provider closure, restart, delayed confirmation, deadline expiry and last-capacity restoration remain separate cutover or database evidence.',
  35: 'Local investigation and guarded resolution are runnable; provider verification, LMNL outbox interruption, and cutover evidence remain deferred.',
  36: 'The local Fake LMNL workflow covers the staff Order read, scheduler recovery boundary, and guarded retry state checks. Deliberate interruption, provider/hosted worker evidence, and cutover testing remain deferred.',
  37: 'Local failed-delivery, guarded resend, verified address correction, and unknown-outcome fencing are runnable; provider, hosted worker, actual email, and cutover testing remain deferred.',
  38: 'The local database verifier covers HP-OS recovery behavior; the Fake dashboard does not reproduce the full buyer-request, delivery, expiry, and wrong-Site suite.',
  39: 'Run the delivery-correction workflow and the local PostgreSQL verifier. Wallet-device/private-approval integration, hosted worker, actual email, and cutover evidence remain deferred.',
  40: 'Run the arrival-change workflow for default check-in timing, per-Order notification jobs, and current Wallet data. LMNL delivery and hosted interruption proof remain deferred.',
  41: 'Run the cancellation workflow for local sales, Admission, Reservation, notification, and refund-state behavior. Provider closure/refund and LMNL delivery proof remain deferred.',
  42: 'Run the refund workflow with synthetic reports; it does not verify provider refund status.',
  43: 'Run the reporting workflow with synthetic fee reports and confirmations; it does not verify provider settlement.',
  44: 'Run the connection-history workflow for frozen mapping snapshots. Operator connection assignment, historical provider access, and real recovery/refund proof remain separate.',
  45: 'Blocked by recovery implementation and real integration evidence in #34–44.',
  46: 'Run private approval for local request, decision, undo, and link-replacement behavior. Email delivery and permission proof remain separate.',
  47: 'Run private purchase for one approved Ticket and separate attendee/purchaser identity. Provider, email, and cutover proof remain separate.',
  48: 'Run unsigned Wallet-data checks. Signing and supported-device proof remain Site-owned.',
  49: 'Run Wallet update-job checks. Apple device service and hosted worker proof remain Site-owned.',
  50: 'Run the public group-purchase workflow after the required preceding stages. External journey proof remains separate.',
  51: 'Blocked by #50 and complete scenario, actual email/Wallet, permissions and physical-device evidence. This dashboard exports individual results; it cannot pass the release checklist.',
  52: 'Hosted SQL, callbacks and scheduled-worker evidence required. Local execution is disabled.',
  53: 'Hosted complete test-payment journeys and supported-device evidence required. Local execution is disabled.',
  54: 'Controlled cutover requires finished existing Events, closed sales, approved environment and preceding release checks. No production action exists here.',
  55: 'Explicit release-owner approval after all required evidence is mandatory. No sales-opening action exists here.',
};
export function ticketChecklist() {
  const runnableTickets = new Set(workflows.map(workflow => workflow.ticket));
  return tickets.map(t => ({
    number: t.number, title: t.title, implementationIssueState: t.state,
    url: `https://github.com/fvckzest/HP-OS/issues/${t.number}`,
    criteria: [...t.body.matchAll(/^- \[[ x]\] (.+)$/gm)].map(m => m[1]),
    gate: t.number >= 51 || [33, 45].includes(t.number) ? 'blocked' : runnableTickets.has(t.number) ? 'not run' : 'unavailable',
    reason: reasons[t.number] ?? 'Run individual workflows explicitly. A passing scenario does not complete every ticket acceptance criterion.',
  }));
}
export function documentedRoutes(...documents) {
  return [...new Set(documents.flatMap(s => [...s.matchAll(/`((?:GET|POST|PATCH|PUT|DELETE) \/v1\/[^`\s]+)`/g)].map(m => m[1])))].sort();
}
